name: common_smals_config
priority: 100
transformations:
  - id: index_condition_linux
    type: add_condition
    conditions:
      index: "*_linux"
    rule_conditions:
      - type: logsource
        product: linux
  - id: index_condition_windows
    type: add_condition
    conditions:
      index: "*_windows"
    rule_conditions:
      - type: logsource
        product: windows
  - id: index_condition_xdr
    type: add_condition
    conditions:
      index: "*_xdr"
    rule_conditions:
      - type: logsource
        category: xdr
  - id: index_condition_m365
    type: add_condition
    conditions:
      index: "*_m365"
    rule_conditions:
      - type: logsource
        product: m365
  - id: index_condition_proxy
    type: add_condition
    conditions:
      index: "*_proxy*"
    rule_conditions:
      - type: logsource
        category: proxy
  - id: index_condition_vpn
    type: add_condition
    conditions:
      index: "*_vpn"
    rule_conditions:
      - type: logsource
        category: vpn
  - id: index_mapping_proxy
    type: field_name_mapping
    mapping:
      cs-host: cs_host
      c-useragent: cs_User_Agent
      cs-method: cs_method
      c-uri: cs_uri_path
      cs-uri: cs_uri_path
      sc-status: sc_status
      c-uri-extension: cs_uri_extension
      cs-ip: c_ip
      ClientIP: c_ip
      c-uri-query: cs_uri_query
    rule_conditions:
      - type: logsource
        category: proxy
